config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :comments
  resources :posts
  root 'staticpages#home'

  get '/friends', to: 'staticpages#friends'

  get '/family', to: 'staticpages#family'

  get '/photos', to: 'staticpages#photos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :username, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :username, presence: true
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to root_path, notice: "comment saved"
    else
      redirect_to root_path, notice: "Your name or comment Can't be blank"
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:username, :content)
    end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to photos_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:caption, :avatar)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :username, :content)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    @posts = Post.order('created_at DESC').limit(2)
    @comments = Comment.all
    @comment = Comment.new
  end

  def friends
  end

  def family
  end

  def photos
    @images = Image.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/comments/_comment.html.erb
<div class="col-sm-10">
  <h4><%= comment.username %><small> <%= time_ago_in_words(comment.created_at) %> ago</small></h4>
  <p><%= comment.content %></p>
  <hr>
</div>

app/views/comments/_new.html.erb
<%= form_for(@comment) do |f| %>
<h4 id="notice"><%= notice %></h4>

  <%= f.label :"Your name" %>
  <%= f.text_field :username %>

  <%= f.label :"leave comment" %>
  <%= f.text_area :content, size: '100x3' %><br>

  <%= f.submit :Submit, :class => 'btn btn-success btn-lg' %>
<% end %>

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"write a caption" %>
    <%= f.text_area :caption %>
  </div>

  <div class="field">
    <%= f.label :"upload image" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit :"submit" %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.avatar.url if image.avatar? %></td>
        <td><%= image.caption %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @image.caption %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_footer.html.erb
  <p id="footer">
    W3schools.com bootstrap blog template example
  </p>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>example blog</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><h3><%= link_to 'New Post', new_post_path %></h3></li>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Friends', friends_path %></li>
        <li><%= link_to 'Family', family_path %></li>
        <li><%= link_to 'Photos', photos_path %></li>
        <li><h3><%= link_to 'All posts', posts_path %></h3></li>
      </ul><br>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W3blogexample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content , size: '50x20' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <h4><span class="glyphicon glyphicon-time"></span><%= post.username %> <%= time_ago_in_words(post.created_at) %> ago</h4>
  <h5><span class="label label-danger">Rails!</span> <span class="label label-primary">Fun!</span></h5>
  <p id="pcontent"><%= post.content %></p>
  <hr>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="col-sm-9">

<h4><small>Most recent Posts towards the top</small></h4>

<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <h4><span class="glyphicon glyphicon-time"></span><%= post.username %>  <small><%= time_ago_in_words(post.created_at) %> ago</small></h4>
  <h5><span class="label label-danger">Rails!</span> <span class="label label-primary">Fun!</span></h5>
  <p class="pcontent"><%= post.content %></p>
  <hr>
<% end %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Username:</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/staticpages/family.html.erb
<div class="text-center">
  <h1>Family</h1>
</div>

app/views/staticpages/friends.html.erb
<div class="text-center">
  <h1>Friends</h1>
</div>

app/views/staticpages/home.html.erb
<div class="col-sm-9">
  <h4><small>The two most recent posts</small></h4>
  <hr>
  <% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <h4><span class="glyphicon glyphicon-time"></span><%= post.username %>  <small><%= time_ago_in_words(post.created_at) %> ago</small></h4>
    <h5><span class="label label-danger">Rails!</span> <span class="label label-primary">Fun!</span></h5>
    <p class="pcontent"><%= post.content %></p>
    <hr>
  <% end %>
  <h4>Leave a Comment Below:</h4>
  <%= render 'comments/new' %>

  <p><span class="badge"><%= Comment.count %></span> Comments:</p>
  <hr>

  <%= render @comments %>

</div>

app/views/staticpages/photos.html.erb
<div class="text-center">
  <h1>Photos</h1>
  <h4><%= link_to 'Add Photo', new_image_path %>
</div>

<% @images.each do |image| %>

  <div id="pimage">
    <%= image_tag image.avatar.url, :class => "pimage" %>
    <h4><small><%= image.caption %></small></h4>
  </div>
<% end %>